### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by tymm**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Can you verify that that's the way it's actually parsed?  It wouldn't surprise me if they weren't consistent.

**Comment by KentShikama** [comment]
```
opXmitTag		= 0x10,		/* Format 4 */

#define OP_f4_op0(x) GET_FW(x,0,4) 
#define OP_f4_nargs(x) GET_FW(x,4,4) 
#define OP_f4_next(x) GET_FW(x,8,1) 
#define OP_f4_unwind(x) GET_FW(x,9,1) 
#define OP_f4_nil(x) GET_FW(x,10,6) 
```

The ordering for anything "format 4" is indeed `0001 00 u n mmmm vvvv` so I think this is a typo too.

**Comment by tymm** [comment]
Thanks Kent.

Also in `Code.cc` we can see it in actual use:
```
        case opXmitTag | NextOff | UnwindOff:
        case opXmitTag | NextOff | UnwindOn:
        case opXmitTag | NextOn  | UnwindOff:
        case opXmitTag | NextOn  | UnwindOn:
            sprintf(buf, "xmit%s%s %d,",
                    OP_f4_unwind(insn) ? "/unwind" : "",
                    OP_f4_next(insn) ? "/nxt" : "",
                    OP_f4_nargs(insn));
            dest.atom = code->lit(OP_f4_op0(insn));
            goto formatDest;
```

**Comment by ghost** [comment]
You addressed this in pull #29, so please close this one.

**Comment by tymm** [comment]
Hmm, you mean #27?
But also there I didn't address it yet.

But since you seem to agree, I'll add the change to #27 now.

**Comment by ghost** [comment]
Yes, #27, sorry.  Thanks!

**Pull request merged**
